# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: forensic-system
  labels:
    name: forensic-system
---
# Evidence Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: evidence-secrets
  namespace: forensic-system
type: Opaque
stringData:
  DATABASE_URL: ""
  MONGODB_URI: ""
  REDIS_URL: ""
  RABBITMQ_URL: ""
  JWT_SECRET: ""
  JWT_REFRESH_SECRET: ""
  ENCRYPTION_KEY: ""
---
# Blockchain Secrets
apiVersion: v1
kind: Secret
metadata:
  name: blockchain-secrets
  namespace: forensic-system
type: Opaque
stringData:
  SEPOLIA_RPC_URL: ""
  AMOY_RPC_URL: ""
  PRIVATE_KEY: ""
  ETHERSCAN_API_KEY: ""
  POLYGONSCAN_API_KEY: ""
---
# AI Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: forensic-system
type: Opaque
stringData:
  OPENAI_API_KEY: ""
---
# Contract Addresses ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: contract-addresses
  namespace: forensic-system
data:
  CONTRACT_ADDRESS_SEPOLIA: ""
  CONTRACT_ADDRESS_AMOY: ""
  BRIDGE_CONTRACT_SEPOLIA: ""
  BRIDGE_CONTRACT_AMOY: ""
---
# Service Configuration ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: forensic-system
data:
  NODE_ENV: "production"
  PORT: "3001"
  IPFS_HOST: "ipfs-service"
  IPFS_PORT: "5001"
  IPFS_PROTOCOL: "http"
  AI_SERVICE_URL: "http://ai-analysis-service:8001"
  MODEL_PATH: "/models"
  NEXT_PUBLIC_API_URL: "http://evidence-service:3001"
  NEXT_PUBLIC_WS_URL: "ws://notification-service:8888"
  NEXT_PUBLIC_SEPOLIA_RPC: ""
  NEXT_PUBLIC_AMOY_RPC: ""
  EVIDENCE_SERVICE_PORT: "3001"
  BLOCKCHAIN_SERVICE_PORT: "3002"
  CROSSCHAIN_SERVICE_PORT: "3003"
  AUTH_SERVICE_PORT: "3004"
  NOTIFICATION_SERVICE_PORT: "3005"
  AI_ANALYSIS_SERVICE_PORT: "8001"
  CORS_ORIGIN: "http://localhost:3000,http://localhost:3001"
  MAX_FILE_SIZE: "104857600"
  ALLOWED_FILE_TYPES: "image/jpeg,image/png,video/mp4,application/pdf"
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3006"
  JWT_EXPIRY: "15m"
  JWT_REFRESH_EXPIRY: "7d"
---
# Database Services
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: forensic-system
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: forensic-system
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: forensic-system
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: forensic-system
spec:
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: 5672
  - port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-service
  namespace: forensic-system
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
  - port: 4001
    targetPort: 4001
  - port: 8080
    targetPort: 8080
  selector:
    app: ipfs
