apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-analysis-config
  namespace: forensic-evidence
data:
  SERVICE_NAME: "ai-analysis-service"
  HOST: "0.0.0.0"
  PORT: "8001"
  ENVIRONMENT: "production"
  DEBUG: "False"
  LOG_LEVEL: "INFO"
  ENABLE_DOCS: "False"
  ENABLE_METRICS: "True"
  ENABLE_IMAGE_ANALYSIS: "True"
  ENABLE_VIDEO_ANALYSIS: "True"
  ENABLE_DOCUMENT_ANALYSIS: "True"
  ENABLE_AUDIO_ANALYSIS: "True"
  TEMP_STORAGE_PATH: "/tmp/ai-analysis"
  MODEL_PATH: "/app/models"
  IMAGE_MAX_SIZE: "52428800"
  VIDEO_MAX_SIZE: "524288000"
  DOCUMENT_MAX_SIZE: "104857600"
  AUDIO_MAX_SIZE: "104857600"
  MAX_CONCURRENT_ANALYSES: "10"
  ANALYSIS_QUEUE_SIZE: "100"
  MODEL_CACHE_SIZE: "5"
  REDIS_TTL: "3600"
  REDIS_MAX_CONNECTIONS: "50"
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "40"
  DB_POOL_TIMEOUT: "30"
  IPFS_TIMEOUT: "30"
  JWT_EXPIRATION_MINUTES: "60"
  MAX_TEMP_FILE_AGE: "3600"
